server:
  port: 443
  http2:
    enabled: true
  # ssl:
  #   enabled: ${ssl_enabled:true}
  #   key-alias:  sm2-selfsign
  #   key-store-password: '123456'
  #   key-store:  classpath:sm2-selfsign.p12
  #   key-store-type: PKCS12
  #   key-store-provider: BC
  #   enabled-protocols:
  #     - TLSv1.2
  #     - TLSv1.3
  #   ciphers:
  #     - TLS_SM4_GCM_SM3
  #     - TLS_SM4_CCM_SM3
  ssl:
    enabled: ${ssl_enabled:true}
    key-alias:  wbcc
    key-store-password: '123456'
    key-store:  classpath:w_b_c_c.p12
    key-store-type: PKCS12

spring:
  application:
    name: "netty-websocket-test"
  main:
    allow-bean-definition-overriding: true
  profiles:
    active: default

thread-pool-props:
  corePoolSize: 5
  maxPoolSize: 100
  keepAliveSeconds: 100
  queueCapacity: 1000