server:
  port: 443
  http2:
    enabled: true
  ssl:
    key-alias:  sm2_sign
    key-store-password: ''
    key-store:  classpath:sm2_sign.p12
    key-store-type: PKCS12
    key-store-provider: BC

spring:
  main:
    allow-bean-definition-overriding: true

thread-pool-props:
  corePoolSize: 5
  maxPoolSize: 100
  keepAliveSeconds: 100
  queueCapacity: 1000