server:
  port: 443
  http2:
    enabled: true
  # ssl:
  #   key-alias:  sm2-selfsign
  #   key-store-password: '123456'
  #   key-store:  classpath:sm2-selfsign.p12
  #   key-store-type: PKCS12
  #   key-store-provider: BC
  #   enabled-protocols:
  #     - TLSv1.2
  #     - TLSv1.3
  #   ciphers:
  #     - TLS_SM4_GCM_SM3
  #     - TLS_SM4_CCM_SM3
  ssl:
    key-alias:  common
    key-store-password: '123456'
    key-store:  classpath:common.p12
    key-store-type: PKCS12

spring:
  main:
    allow-bean-definition-overriding: true

thread-pool-props:
  corePoolSize: 5
  maxPoolSize: 100
  keepAliveSeconds: 100
  queueCapacity: 1000