// Generated by the protocol buffer compiler.  DO NOT EDIT!
// source: WebSocketMessages.proto

package group.bison.netty.protoc.messages;

public final class WebSocketMessages {
  private WebSocketMessages() {}
  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistryLite registry) {
  }

  public static void registerAllExtensions(
      com.google.protobuf.ExtensionRegistry registry) {
    registerAllExtensions(
        (com.google.protobuf.ExtensionRegistryLite) registry);
  }
  /**
   * Protobuf enum {@code group.bison.netty.protoc.messages.Event}
   */
  public enum Event
      implements com.google.protobuf.ProtocolMessageEnum {
    /**
     * <code>ON_LINE = 0;</code>
     */
    ON_LINE(0),
    /**
     * <code>BIND = 1;</code>
     */
    BIND(1),
    UNRECOGNIZED(-1),
    ;

    /**
     * <code>ON_LINE = 0;</code>
     */
    public static final int ON_LINE_VALUE = 0;
    /**
     * <code>BIND = 1;</code>
     */
    public static final int BIND_VALUE = 1;


    public final int getNumber() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalArgumentException(
            "Can't get the number of an unknown enum value.");
      }
      return value;
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     * @deprecated Use {@link #forNumber(int)} instead.
     */
    @java.lang.Deprecated
    public static Event valueOf(int value) {
      return forNumber(value);
    }

    /**
     * @param value The numeric wire value of the corresponding enum entry.
     * @return The enum associated with the given numeric wire value.
     */
    public static Event forNumber(int value) {
      switch (value) {
        case 0: return ON_LINE;
        case 1: return BIND;
        default: return null;
      }
    }

    public static com.google.protobuf.Internal.EnumLiteMap<Event>
        internalGetValueMap() {
      return internalValueMap;
    }
    private static final com.google.protobuf.Internal.EnumLiteMap<
        Event> internalValueMap =
          new com.google.protobuf.Internal.EnumLiteMap<Event>() {
            public Event findValueByNumber(int number) {
              return Event.forNumber(number);
            }
          };

    public final com.google.protobuf.Descriptors.EnumValueDescriptor
        getValueDescriptor() {
      if (this == UNRECOGNIZED) {
        throw new java.lang.IllegalStateException(
            "Can't get the descriptor of an unrecognized enum value.");
      }
      return getDescriptor().getValues().get(ordinal());
    }
    public final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptorForType() {
      return getDescriptor();
    }
    public static final com.google.protobuf.Descriptors.EnumDescriptor
        getDescriptor() {
      return group.bison.netty.protoc.messages.WebSocketMessages.getDescriptor().getEnumTypes().get(0);
    }

    private static final Event[] VALUES = values();

    public static Event valueOf(
        com.google.protobuf.Descriptors.EnumValueDescriptor desc) {
      if (desc.getType() != getDescriptor()) {
        throw new java.lang.IllegalArgumentException(
          "EnumValueDescriptor is not for this type.");
      }
      if (desc.getIndex() == -1) {
        return UNRECOGNIZED;
      }
      return VALUES[desc.getIndex()];
    }

    private final int value;

    private Event(int value) {
      this.value = value;
    }

    // @@protoc_insertion_point(enum_scope:group.bison.netty.protoc.messages.Event)
  }

  public interface WebsocketRequestOrBuilder extends
      // @@protoc_insertion_point(interface_extends:group.bison.netty.protoc.messages.WebsocketRequest)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>.group.bison.netty.protoc.messages.Event event = 1;</code>
     * @return The enum numeric value on the wire for event.
     */
    int getEventValue();
    /**
     * <code>.group.bison.netty.protoc.messages.Event event = 1;</code>
     * @return The event.
     */
    group.bison.netty.protoc.messages.WebSocketMessages.Event getEvent();

    /**
     * <code>.google.protobuf.Any value = 2;</code>
     * @return Whether the value field is set.
     */
    boolean hasValue();
    /**
     * <code>.google.protobuf.Any value = 2;</code>
     * @return The value.
     */
    com.google.protobuf.Any getValue();
    /**
     * <code>.google.protobuf.Any value = 2;</code>
     */
    com.google.protobuf.AnyOrBuilder getValueOrBuilder();
  }
  /**
   * <pre>
   * websocket请求消息体
   * </pre>
   *
   * Protobuf type {@code group.bison.netty.protoc.messages.WebsocketRequest}
   */
  public static final class WebsocketRequest extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:group.bison.netty.protoc.messages.WebsocketRequest)
      WebsocketRequestOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WebsocketRequest.newBuilder() to construct.
    private WebsocketRequest(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WebsocketRequest() {
      event_ = 0;
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WebsocketRequest();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_WebsocketRequest_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_WebsocketRequest_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest.class, group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest.Builder.class);
    }

    public static final int EVENT_FIELD_NUMBER = 1;
    private int event_;
    /**
     * <code>.group.bison.netty.protoc.messages.Event event = 1;</code>
     * @return The enum numeric value on the wire for event.
     */
    @java.lang.Override public int getEventValue() {
      return event_;
    }
    /**
     * <code>.group.bison.netty.protoc.messages.Event event = 1;</code>
     * @return The event.
     */
    @java.lang.Override public group.bison.netty.protoc.messages.WebSocketMessages.Event getEvent() {
      @SuppressWarnings("deprecation")
      group.bison.netty.protoc.messages.WebSocketMessages.Event result = group.bison.netty.protoc.messages.WebSocketMessages.Event.valueOf(event_);
      return result == null ? group.bison.netty.protoc.messages.WebSocketMessages.Event.UNRECOGNIZED : result;
    }

    public static final int VALUE_FIELD_NUMBER = 2;
    private com.google.protobuf.Any value_;
    /**
     * <code>.google.protobuf.Any value = 2;</code>
     * @return Whether the value field is set.
     */
    @java.lang.Override
    public boolean hasValue() {
      return value_ != null;
    }
    /**
     * <code>.google.protobuf.Any value = 2;</code>
     * @return The value.
     */
    @java.lang.Override
    public com.google.protobuf.Any getValue() {
      return value_ == null ? com.google.protobuf.Any.getDefaultInstance() : value_;
    }
    /**
     * <code>.google.protobuf.Any value = 2;</code>
     */
    @java.lang.Override
    public com.google.protobuf.AnyOrBuilder getValueOrBuilder() {
      return getValue();
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (event_ != group.bison.netty.protoc.messages.WebSocketMessages.Event.ON_LINE.getNumber()) {
        output.writeEnum(1, event_);
      }
      if (value_ != null) {
        output.writeMessage(2, getValue());
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (event_ != group.bison.netty.protoc.messages.WebSocketMessages.Event.ON_LINE.getNumber()) {
        size += com.google.protobuf.CodedOutputStream
          .computeEnumSize(1, event_);
      }
      if (value_ != null) {
        size += com.google.protobuf.CodedOutputStream
          .computeMessageSize(2, getValue());
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest)) {
        return super.equals(obj);
      }
      group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest other = (group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest) obj;

      if (event_ != other.event_) return false;
      if (hasValue() != other.hasValue()) return false;
      if (hasValue()) {
        if (!getValue()
            .equals(other.getValue())) return false;
      }
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + EVENT_FIELD_NUMBER;
      hash = (53 * hash) + event_;
      if (hasValue()) {
        hash = (37 * hash) + VALUE_FIELD_NUMBER;
        hash = (53 * hash) + getValue().hashCode();
      }
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * websocket请求消息体
     * </pre>
     *
     * Protobuf type {@code group.bison.netty.protoc.messages.WebsocketRequest}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:group.bison.netty.protoc.messages.WebsocketRequest)
        group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequestOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_WebsocketRequest_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_WebsocketRequest_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest.class, group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest.Builder.class);
      }

      // Construct using group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        event_ = 0;

        if (valueBuilder_ == null) {
          value_ = null;
        } else {
          value_ = null;
          valueBuilder_ = null;
        }
        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_WebsocketRequest_descriptor;
      }

      @java.lang.Override
      public group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest getDefaultInstanceForType() {
        return group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest.getDefaultInstance();
      }

      @java.lang.Override
      public group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest build() {
        group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest buildPartial() {
        group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest result = new group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest(this);
        result.event_ = event_;
        if (valueBuilder_ == null) {
          result.value_ = value_;
        } else {
          result.value_ = valueBuilder_.build();
        }
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest) {
          return mergeFrom((group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest other) {
        if (other == group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest.getDefaultInstance()) return this;
        if (other.event_ != 0) {
          setEventValue(other.getEventValue());
        }
        if (other.hasValue()) {
          mergeValue(other.getValue());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                event_ = input.readEnum();

                break;
              } // case 8
              case 18: {
                input.readMessage(
                    getValueFieldBuilder().getBuilder(),
                    extensionRegistry);

                break;
              } // case 18
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int event_ = 0;
      /**
       * <code>.group.bison.netty.protoc.messages.Event event = 1;</code>
       * @return The enum numeric value on the wire for event.
       */
      @java.lang.Override public int getEventValue() {
        return event_;
      }
      /**
       * <code>.group.bison.netty.protoc.messages.Event event = 1;</code>
       * @param value The enum numeric value on the wire for event to set.
       * @return This builder for chaining.
       */
      public Builder setEventValue(int value) {
        
        event_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>.group.bison.netty.protoc.messages.Event event = 1;</code>
       * @return The event.
       */
      @java.lang.Override
      public group.bison.netty.protoc.messages.WebSocketMessages.Event getEvent() {
        @SuppressWarnings("deprecation")
        group.bison.netty.protoc.messages.WebSocketMessages.Event result = group.bison.netty.protoc.messages.WebSocketMessages.Event.valueOf(event_);
        return result == null ? group.bison.netty.protoc.messages.WebSocketMessages.Event.UNRECOGNIZED : result;
      }
      /**
       * <code>.group.bison.netty.protoc.messages.Event event = 1;</code>
       * @param value The event to set.
       * @return This builder for chaining.
       */
      public Builder setEvent(group.bison.netty.protoc.messages.WebSocketMessages.Event value) {
        if (value == null) {
          throw new NullPointerException();
        }
        
        event_ = value.getNumber();
        onChanged();
        return this;
      }
      /**
       * <code>.group.bison.netty.protoc.messages.Event event = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearEvent() {
        
        event_ = 0;
        onChanged();
        return this;
      }

      private com.google.protobuf.Any value_;
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> valueBuilder_;
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       * @return Whether the value field is set.
       */
      public boolean hasValue() {
        return valueBuilder_ != null || value_ != null;
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       * @return The value.
       */
      public com.google.protobuf.Any getValue() {
        if (valueBuilder_ == null) {
          return value_ == null ? com.google.protobuf.Any.getDefaultInstance() : value_;
        } else {
          return valueBuilder_.getMessage();
        }
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public Builder setValue(com.google.protobuf.Any value) {
        if (valueBuilder_ == null) {
          if (value == null) {
            throw new NullPointerException();
          }
          value_ = value;
          onChanged();
        } else {
          valueBuilder_.setMessage(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public Builder setValue(
          com.google.protobuf.Any.Builder builderForValue) {
        if (valueBuilder_ == null) {
          value_ = builderForValue.build();
          onChanged();
        } else {
          valueBuilder_.setMessage(builderForValue.build());
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public Builder mergeValue(com.google.protobuf.Any value) {
        if (valueBuilder_ == null) {
          if (value_ != null) {
            value_ =
              com.google.protobuf.Any.newBuilder(value_).mergeFrom(value).buildPartial();
          } else {
            value_ = value;
          }
          onChanged();
        } else {
          valueBuilder_.mergeFrom(value);
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public Builder clearValue() {
        if (valueBuilder_ == null) {
          value_ = null;
          onChanged();
        } else {
          value_ = null;
          valueBuilder_ = null;
        }

        return this;
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public com.google.protobuf.Any.Builder getValueBuilder() {
        
        onChanged();
        return getValueFieldBuilder().getBuilder();
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       */
      public com.google.protobuf.AnyOrBuilder getValueOrBuilder() {
        if (valueBuilder_ != null) {
          return valueBuilder_.getMessageOrBuilder();
        } else {
          return value_ == null ?
              com.google.protobuf.Any.getDefaultInstance() : value_;
        }
      }
      /**
       * <code>.google.protobuf.Any value = 2;</code>
       */
      private com.google.protobuf.SingleFieldBuilderV3<
          com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder> 
          getValueFieldBuilder() {
        if (valueBuilder_ == null) {
          valueBuilder_ = new com.google.protobuf.SingleFieldBuilderV3<
              com.google.protobuf.Any, com.google.protobuf.Any.Builder, com.google.protobuf.AnyOrBuilder>(
                  getValue(),
                  getParentForChildren(),
                  isClean());
          value_ = null;
        }
        return valueBuilder_;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:group.bison.netty.protoc.messages.WebsocketRequest)
    }

    // @@protoc_insertion_point(class_scope:group.bison.netty.protoc.messages.WebsocketRequest)
    private static final group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest();
    }

    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WebsocketRequest>
        PARSER = new com.google.protobuf.AbstractParser<WebsocketRequest>() {
      @java.lang.Override
      public WebsocketRequest parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WebsocketRequest> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WebsocketRequest> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public group.bison.netty.protoc.messages.WebSocketMessages.WebsocketRequest getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface WebsocketResponseOrBuilder extends
      // @@protoc_insertion_point(interface_extends:group.bison.netty.protoc.messages.WebsocketResponse)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>int32 code = 2;</code>
     * @return The code.
     */
    int getCode();

    /**
     * <code>string message = 3;</code>
     * @return The message.
     */
    java.lang.String getMessage();
    /**
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    com.google.protobuf.ByteString
        getMessageBytes();
  }
  /**
   * <pre>
   * websocket的响应体
   * </pre>
   *
   * Protobuf type {@code group.bison.netty.protoc.messages.WebsocketResponse}
   */
  public static final class WebsocketResponse extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:group.bison.netty.protoc.messages.WebsocketResponse)
      WebsocketResponseOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use WebsocketResponse.newBuilder() to construct.
    private WebsocketResponse(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private WebsocketResponse() {
      message_ = "";
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new WebsocketResponse();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_WebsocketResponse_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_WebsocketResponse_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse.class, group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse.Builder.class);
    }

    public static final int CODE_FIELD_NUMBER = 2;
    private int code_;
    /**
     * <code>int32 code = 2;</code>
     * @return The code.
     */
    @java.lang.Override
    public int getCode() {
      return code_;
    }

    public static final int MESSAGE_FIELD_NUMBER = 3;
    private volatile java.lang.Object message_;
    /**
     * <code>string message = 3;</code>
     * @return The message.
     */
    @java.lang.Override
    public java.lang.String getMessage() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        return (java.lang.String) ref;
      } else {
        com.google.protobuf.ByteString bs = 
            (com.google.protobuf.ByteString) ref;
        java.lang.String s = bs.toStringUtf8();
        message_ = s;
        return s;
      }
    }
    /**
     * <code>string message = 3;</code>
     * @return The bytes for message.
     */
    @java.lang.Override
    public com.google.protobuf.ByteString
        getMessageBytes() {
      java.lang.Object ref = message_;
      if (ref instanceof java.lang.String) {
        com.google.protobuf.ByteString b = 
            com.google.protobuf.ByteString.copyFromUtf8(
                (java.lang.String) ref);
        message_ = b;
        return b;
      } else {
        return (com.google.protobuf.ByteString) ref;
      }
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (code_ != 0) {
        output.writeInt32(2, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        com.google.protobuf.GeneratedMessageV3.writeString(output, 3, message_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (code_ != 0) {
        size += com.google.protobuf.CodedOutputStream
          .computeInt32Size(2, code_);
      }
      if (!com.google.protobuf.GeneratedMessageV3.isStringEmpty(message_)) {
        size += com.google.protobuf.GeneratedMessageV3.computeStringSize(3, message_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse)) {
        return super.equals(obj);
      }
      group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse other = (group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse) obj;

      if (getCode()
          != other.getCode()) return false;
      if (!getMessage()
          .equals(other.getMessage())) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + CODE_FIELD_NUMBER;
      hash = (53 * hash) + getCode();
      hash = (37 * hash) + MESSAGE_FIELD_NUMBER;
      hash = (53 * hash) + getMessage().hashCode();
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * websocket的响应体
     * </pre>
     *
     * Protobuf type {@code group.bison.netty.protoc.messages.WebsocketResponse}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:group.bison.netty.protoc.messages.WebsocketResponse)
        group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponseOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_WebsocketResponse_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_WebsocketResponse_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse.class, group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse.Builder.class);
      }

      // Construct using group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        code_ = 0;

        message_ = "";

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_WebsocketResponse_descriptor;
      }

      @java.lang.Override
      public group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse getDefaultInstanceForType() {
        return group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse.getDefaultInstance();
      }

      @java.lang.Override
      public group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse build() {
        group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse buildPartial() {
        group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse result = new group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse(this);
        result.code_ = code_;
        result.message_ = message_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse) {
          return mergeFrom((group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse other) {
        if (other == group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse.getDefaultInstance()) return this;
        if (other.getCode() != 0) {
          setCode(other.getCode());
        }
        if (!other.getMessage().isEmpty()) {
          message_ = other.message_;
          onChanged();
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 16: {
                code_ = input.readInt32();

                break;
              } // case 16
              case 26: {
                message_ = input.readStringRequireUtf8();

                break;
              } // case 26
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private int code_ ;
      /**
       * <code>int32 code = 2;</code>
       * @return The code.
       */
      @java.lang.Override
      public int getCode() {
        return code_;
      }
      /**
       * <code>int32 code = 2;</code>
       * @param value The code to set.
       * @return This builder for chaining.
       */
      public Builder setCode(int value) {
        
        code_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>int32 code = 2;</code>
       * @return This builder for chaining.
       */
      public Builder clearCode() {
        
        code_ = 0;
        onChanged();
        return this;
      }

      private java.lang.Object message_ = "";
      /**
       * <code>string message = 3;</code>
       * @return The message.
       */
      public java.lang.String getMessage() {
        java.lang.Object ref = message_;
        if (!(ref instanceof java.lang.String)) {
          com.google.protobuf.ByteString bs =
              (com.google.protobuf.ByteString) ref;
          java.lang.String s = bs.toStringUtf8();
          message_ = s;
          return s;
        } else {
          return (java.lang.String) ref;
        }
      }
      /**
       * <code>string message = 3;</code>
       * @return The bytes for message.
       */
      public com.google.protobuf.ByteString
          getMessageBytes() {
        java.lang.Object ref = message_;
        if (ref instanceof String) {
          com.google.protobuf.ByteString b = 
              com.google.protobuf.ByteString.copyFromUtf8(
                  (java.lang.String) ref);
          message_ = b;
          return b;
        } else {
          return (com.google.protobuf.ByteString) ref;
        }
      }
      /**
       * <code>string message = 3;</code>
       * @param value The message to set.
       * @return This builder for chaining.
       */
      public Builder setMessage(
          java.lang.String value) {
        if (value == null) {
    throw new NullPointerException();
  }
  
        message_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>string message = 3;</code>
       * @return This builder for chaining.
       */
      public Builder clearMessage() {
        
        message_ = getDefaultInstance().getMessage();
        onChanged();
        return this;
      }
      /**
       * <code>string message = 3;</code>
       * @param value The bytes for message to set.
       * @return This builder for chaining.
       */
      public Builder setMessageBytes(
          com.google.protobuf.ByteString value) {
        if (value == null) {
    throw new NullPointerException();
  }
  checkByteStringIsUtf8(value);
        
        message_ = value;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:group.bison.netty.protoc.messages.WebsocketResponse)
    }

    // @@protoc_insertion_point(class_scope:group.bison.netty.protoc.messages.WebsocketResponse)
    private static final group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse();
    }

    public static group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<WebsocketResponse>
        PARSER = new com.google.protobuf.AbstractParser<WebsocketResponse>() {
      @java.lang.Override
      public WebsocketResponse parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<WebsocketResponse> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<WebsocketResponse> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public group.bison.netty.protoc.messages.WebSocketMessages.WebsocketResponse getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  public interface StatusReportValueOrBuilder extends
      // @@protoc_insertion_point(interface_extends:group.bison.netty.protoc.messages.StatusReportValue)
      com.google.protobuf.MessageOrBuilder {

    /**
     * <code>bool online = 1;</code>
     * @return The online.
     */
    boolean getOnline();
  }
  /**
   * <pre>
   * 鉴权请求
   * </pre>
   *
   * Protobuf type {@code group.bison.netty.protoc.messages.StatusReportValue}
   */
  public static final class StatusReportValue extends
      com.google.protobuf.GeneratedMessageV3 implements
      // @@protoc_insertion_point(message_implements:group.bison.netty.protoc.messages.StatusReportValue)
      StatusReportValueOrBuilder {
  private static final long serialVersionUID = 0L;
    // Use StatusReportValue.newBuilder() to construct.
    private StatusReportValue(com.google.protobuf.GeneratedMessageV3.Builder<?> builder) {
      super(builder);
    }
    private StatusReportValue() {
    }

    @java.lang.Override
    @SuppressWarnings({"unused"})
    protected java.lang.Object newInstance(
        UnusedPrivateParameter unused) {
      return new StatusReportValue();
    }

    @java.lang.Override
    public final com.google.protobuf.UnknownFieldSet
    getUnknownFields() {
      return this.unknownFields;
    }
    public static final com.google.protobuf.Descriptors.Descriptor
        getDescriptor() {
      return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_StatusReportValue_descriptor;
    }

    @java.lang.Override
    protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
        internalGetFieldAccessorTable() {
      return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_StatusReportValue_fieldAccessorTable
          .ensureFieldAccessorsInitialized(
              group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue.class, group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue.Builder.class);
    }

    public static final int ONLINE_FIELD_NUMBER = 1;
    private boolean online_;
    /**
     * <code>bool online = 1;</code>
     * @return The online.
     */
    @java.lang.Override
    public boolean getOnline() {
      return online_;
    }

    private byte memoizedIsInitialized = -1;
    @java.lang.Override
    public final boolean isInitialized() {
      byte isInitialized = memoizedIsInitialized;
      if (isInitialized == 1) return true;
      if (isInitialized == 0) return false;

      memoizedIsInitialized = 1;
      return true;
    }

    @java.lang.Override
    public void writeTo(com.google.protobuf.CodedOutputStream output)
                        throws java.io.IOException {
      if (online_ != false) {
        output.writeBool(1, online_);
      }
      getUnknownFields().writeTo(output);
    }

    @java.lang.Override
    public int getSerializedSize() {
      int size = memoizedSize;
      if (size != -1) return size;

      size = 0;
      if (online_ != false) {
        size += com.google.protobuf.CodedOutputStream
          .computeBoolSize(1, online_);
      }
      size += getUnknownFields().getSerializedSize();
      memoizedSize = size;
      return size;
    }

    @java.lang.Override
    public boolean equals(final java.lang.Object obj) {
      if (obj == this) {
       return true;
      }
      if (!(obj instanceof group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue)) {
        return super.equals(obj);
      }
      group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue other = (group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue) obj;

      if (getOnline()
          != other.getOnline()) return false;
      if (!getUnknownFields().equals(other.getUnknownFields())) return false;
      return true;
    }

    @java.lang.Override
    public int hashCode() {
      if (memoizedHashCode != 0) {
        return memoizedHashCode;
      }
      int hash = 41;
      hash = (19 * hash) + getDescriptor().hashCode();
      hash = (37 * hash) + ONLINE_FIELD_NUMBER;
      hash = (53 * hash) + com.google.protobuf.Internal.hashBoolean(
          getOnline());
      hash = (29 * hash) + getUnknownFields().hashCode();
      memoizedHashCode = hash;
      return hash;
    }

    public static group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue parseFrom(
        java.nio.ByteBuffer data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue parseFrom(
        java.nio.ByteBuffer data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue parseFrom(
        com.google.protobuf.ByteString data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue parseFrom(
        com.google.protobuf.ByteString data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue parseFrom(byte[] data)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue parseFrom(
        byte[] data,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws com.google.protobuf.InvalidProtocolBufferException {
      return PARSER.parseFrom(data, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue parseFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue parseFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue parseDelimitedFrom(java.io.InputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue parseDelimitedFrom(
        java.io.InputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseDelimitedWithIOException(PARSER, input, extensionRegistry);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue parseFrom(
        com.google.protobuf.CodedInputStream input)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input);
    }
    public static group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue parseFrom(
        com.google.protobuf.CodedInputStream input,
        com.google.protobuf.ExtensionRegistryLite extensionRegistry)
        throws java.io.IOException {
      return com.google.protobuf.GeneratedMessageV3
          .parseWithIOException(PARSER, input, extensionRegistry);
    }

    @java.lang.Override
    public Builder newBuilderForType() { return newBuilder(); }
    public static Builder newBuilder() {
      return DEFAULT_INSTANCE.toBuilder();
    }
    public static Builder newBuilder(group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue prototype) {
      return DEFAULT_INSTANCE.toBuilder().mergeFrom(prototype);
    }
    @java.lang.Override
    public Builder toBuilder() {
      return this == DEFAULT_INSTANCE
          ? new Builder() : new Builder().mergeFrom(this);
    }

    @java.lang.Override
    protected Builder newBuilderForType(
        com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
      Builder builder = new Builder(parent);
      return builder;
    }
    /**
     * <pre>
     * 鉴权请求
     * </pre>
     *
     * Protobuf type {@code group.bison.netty.protoc.messages.StatusReportValue}
     */
    public static final class Builder extends
        com.google.protobuf.GeneratedMessageV3.Builder<Builder> implements
        // @@protoc_insertion_point(builder_implements:group.bison.netty.protoc.messages.StatusReportValue)
        group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValueOrBuilder {
      public static final com.google.protobuf.Descriptors.Descriptor
          getDescriptor() {
        return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_StatusReportValue_descriptor;
      }

      @java.lang.Override
      protected com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
          internalGetFieldAccessorTable() {
        return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_StatusReportValue_fieldAccessorTable
            .ensureFieldAccessorsInitialized(
                group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue.class, group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue.Builder.class);
      }

      // Construct using group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue.newBuilder()
      private Builder() {

      }

      private Builder(
          com.google.protobuf.GeneratedMessageV3.BuilderParent parent) {
        super(parent);

      }
      @java.lang.Override
      public Builder clear() {
        super.clear();
        online_ = false;

        return this;
      }

      @java.lang.Override
      public com.google.protobuf.Descriptors.Descriptor
          getDescriptorForType() {
        return group.bison.netty.protoc.messages.WebSocketMessages.internal_static_group_bison_netty_protoc_messages_StatusReportValue_descriptor;
      }

      @java.lang.Override
      public group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue getDefaultInstanceForType() {
        return group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue.getDefaultInstance();
      }

      @java.lang.Override
      public group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue build() {
        group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue result = buildPartial();
        if (!result.isInitialized()) {
          throw newUninitializedMessageException(result);
        }
        return result;
      }

      @java.lang.Override
      public group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue buildPartial() {
        group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue result = new group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue(this);
        result.online_ = online_;
        onBuilt();
        return result;
      }

      @java.lang.Override
      public Builder clone() {
        return super.clone();
      }
      @java.lang.Override
      public Builder setField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.setField(field, value);
      }
      @java.lang.Override
      public Builder clearField(
          com.google.protobuf.Descriptors.FieldDescriptor field) {
        return super.clearField(field);
      }
      @java.lang.Override
      public Builder clearOneof(
          com.google.protobuf.Descriptors.OneofDescriptor oneof) {
        return super.clearOneof(oneof);
      }
      @java.lang.Override
      public Builder setRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          int index, java.lang.Object value) {
        return super.setRepeatedField(field, index, value);
      }
      @java.lang.Override
      public Builder addRepeatedField(
          com.google.protobuf.Descriptors.FieldDescriptor field,
          java.lang.Object value) {
        return super.addRepeatedField(field, value);
      }
      @java.lang.Override
      public Builder mergeFrom(com.google.protobuf.Message other) {
        if (other instanceof group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue) {
          return mergeFrom((group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue)other);
        } else {
          super.mergeFrom(other);
          return this;
        }
      }

      public Builder mergeFrom(group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue other) {
        if (other == group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue.getDefaultInstance()) return this;
        if (other.getOnline() != false) {
          setOnline(other.getOnline());
        }
        this.mergeUnknownFields(other.getUnknownFields());
        onChanged();
        return this;
      }

      @java.lang.Override
      public final boolean isInitialized() {
        return true;
      }

      @java.lang.Override
      public Builder mergeFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws java.io.IOException {
        if (extensionRegistry == null) {
          throw new java.lang.NullPointerException();
        }
        try {
          boolean done = false;
          while (!done) {
            int tag = input.readTag();
            switch (tag) {
              case 0:
                done = true;
                break;
              case 8: {
                online_ = input.readBool();

                break;
              } // case 8
              default: {
                if (!super.parseUnknownField(input, extensionRegistry, tag)) {
                  done = true; // was an endgroup tag
                }
                break;
              } // default:
            } // switch (tag)
          } // while (!done)
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.unwrapIOException();
        } finally {
          onChanged();
        } // finally
        return this;
      }

      private boolean online_ ;
      /**
       * <code>bool online = 1;</code>
       * @return The online.
       */
      @java.lang.Override
      public boolean getOnline() {
        return online_;
      }
      /**
       * <code>bool online = 1;</code>
       * @param value The online to set.
       * @return This builder for chaining.
       */
      public Builder setOnline(boolean value) {
        
        online_ = value;
        onChanged();
        return this;
      }
      /**
       * <code>bool online = 1;</code>
       * @return This builder for chaining.
       */
      public Builder clearOnline() {
        
        online_ = false;
        onChanged();
        return this;
      }
      @java.lang.Override
      public final Builder setUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.setUnknownFields(unknownFields);
      }

      @java.lang.Override
      public final Builder mergeUnknownFields(
          final com.google.protobuf.UnknownFieldSet unknownFields) {
        return super.mergeUnknownFields(unknownFields);
      }


      // @@protoc_insertion_point(builder_scope:group.bison.netty.protoc.messages.StatusReportValue)
    }

    // @@protoc_insertion_point(class_scope:group.bison.netty.protoc.messages.StatusReportValue)
    private static final group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue DEFAULT_INSTANCE;
    static {
      DEFAULT_INSTANCE = new group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue();
    }

    public static group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue getDefaultInstance() {
      return DEFAULT_INSTANCE;
    }

    private static final com.google.protobuf.Parser<StatusReportValue>
        PARSER = new com.google.protobuf.AbstractParser<StatusReportValue>() {
      @java.lang.Override
      public StatusReportValue parsePartialFrom(
          com.google.protobuf.CodedInputStream input,
          com.google.protobuf.ExtensionRegistryLite extensionRegistry)
          throws com.google.protobuf.InvalidProtocolBufferException {
        Builder builder = newBuilder();
        try {
          builder.mergeFrom(input, extensionRegistry);
        } catch (com.google.protobuf.InvalidProtocolBufferException e) {
          throw e.setUnfinishedMessage(builder.buildPartial());
        } catch (com.google.protobuf.UninitializedMessageException e) {
          throw e.asInvalidProtocolBufferException().setUnfinishedMessage(builder.buildPartial());
        } catch (java.io.IOException e) {
          throw new com.google.protobuf.InvalidProtocolBufferException(e)
              .setUnfinishedMessage(builder.buildPartial());
        }
        return builder.buildPartial();
      }
    };

    public static com.google.protobuf.Parser<StatusReportValue> parser() {
      return PARSER;
    }

    @java.lang.Override
    public com.google.protobuf.Parser<StatusReportValue> getParserForType() {
      return PARSER;
    }

    @java.lang.Override
    public group.bison.netty.protoc.messages.WebSocketMessages.StatusReportValue getDefaultInstanceForType() {
      return DEFAULT_INSTANCE;
    }

  }

  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_group_bison_netty_protoc_messages_WebsocketRequest_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_group_bison_netty_protoc_messages_WebsocketRequest_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_group_bison_netty_protoc_messages_WebsocketResponse_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_group_bison_netty_protoc_messages_WebsocketResponse_fieldAccessorTable;
  private static final com.google.protobuf.Descriptors.Descriptor
    internal_static_group_bison_netty_protoc_messages_StatusReportValue_descriptor;
  private static final 
    com.google.protobuf.GeneratedMessageV3.FieldAccessorTable
      internal_static_group_bison_netty_protoc_messages_StatusReportValue_fieldAccessorTable;

  public static com.google.protobuf.Descriptors.FileDescriptor
      getDescriptor() {
    return descriptor;
  }
  private static  com.google.protobuf.Descriptors.FileDescriptor
      descriptor;
  static {
    java.lang.String[] descriptorData = {
      "\n\027WebSocketMessages.proto\022!group.bison.n" +
      "etty.protoc.messages\032\031google/protobuf/an" +
      "y.proto\"p\n\020WebsocketRequest\0227\n\005event\030\001 \001" +
      "(\0162(.group.bison.netty.protoc.messages.E" +
      "vent\022#\n\005value\030\002 \001(\0132\024.google.protobuf.An" +
      "y\"2\n\021WebsocketResponse\022\014\n\004code\030\002 \001(\005\022\017\n\007" +
      "message\030\003 \001(\t\"#\n\021StatusReportValue\022\016\n\006on" +
      "line\030\001 \001(\010*\036\n\005Event\022\013\n\007ON_LINE\020\000\022\010\n\004BIND" +
      "\020\001b\006proto3"
    };
    descriptor = com.google.protobuf.Descriptors.FileDescriptor
      .internalBuildGeneratedFileFrom(descriptorData,
        new com.google.protobuf.Descriptors.FileDescriptor[] {
          com.google.protobuf.AnyProto.getDescriptor(),
        });
    internal_static_group_bison_netty_protoc_messages_WebsocketRequest_descriptor =
      getDescriptor().getMessageTypes().get(0);
    internal_static_group_bison_netty_protoc_messages_WebsocketRequest_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_group_bison_netty_protoc_messages_WebsocketRequest_descriptor,
        new java.lang.String[] { "Event", "Value", });
    internal_static_group_bison_netty_protoc_messages_WebsocketResponse_descriptor =
      getDescriptor().getMessageTypes().get(1);
    internal_static_group_bison_netty_protoc_messages_WebsocketResponse_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_group_bison_netty_protoc_messages_WebsocketResponse_descriptor,
        new java.lang.String[] { "Code", "Message", });
    internal_static_group_bison_netty_protoc_messages_StatusReportValue_descriptor =
      getDescriptor().getMessageTypes().get(2);
    internal_static_group_bison_netty_protoc_messages_StatusReportValue_fieldAccessorTable = new
      com.google.protobuf.GeneratedMessageV3.FieldAccessorTable(
        internal_static_group_bison_netty_protoc_messages_StatusReportValue_descriptor,
        new java.lang.String[] { "Online", });
    com.google.protobuf.AnyProto.getDescriptor();
  }

  // @@protoc_insertion_point(outer_class_scope)
}
