name: Build Docker Image  
  
on:  
  push:  
    branches: [ docker ]  
  pull_request:  
    branches: [ docker ]  
  
jobs:  
  build:  
    runs-on: ubuntu-latest 
    timeout-minutes: 90 
    steps:  
      - name: Checkout Code  
        uses: actions/checkout@v2  
      - name: Compile And Install Modules  
        run: cd modules && pwd && mvn clean install -DskipTests=true -q
        timeout-minutes: 10
      - name: Compile And Package Jars  
        run: pwd && mvn clean package -DskipTests=true -q
        timeout-minutes: 10
      - name: Prepare Docker Cross Compile
        run: docker run --rm --privileged docker/binfmt:a7996909642ee92942dcd6cff44b9b95f08dad64 && docker buildx create --use --name multi-arch-builder
        timeout-minutes: 10
      - name: Build Docker Image  
        run: docker buildx build --platform linux/amd64 --build-arg JAR_FILE=netty-websocket-test-1.0.0-SNAPSHOT-ark-biz.jar . -t registry.cn-beijing.aliyuncs.com/dbsnolimit/netty-websocket:latest  
        timeout-minutes: 60
      - name: Login To Aliyun Docker Registry 
        uses: docker/login-action@v1
        with:
          registry: registry.cn-beijing.aliyuncs.com
          username: ${{ secrets.DOCKER_USERNAME }}  
          password: ${{ secrets.DOCKER_PASSWORD }}  
      - name: Push Docker Image to aliyun docker registry   
        run: docker push registry.cn-beijing.aliyuncs.com/dbsnolimit/netty-websocket:latest
        timeout-minutes: 10
